services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
      - ./basyx/rules/aas_env_rbac_rules.json:/application/rbac_rules.json
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
    networks:
        - basyx-java-server-sdk
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
      - ./basyx/rules/aas_registry_rbac_rules.json:/workspace/config/rbac_rules.json
    restart: always
    networks:
        - basyx-java-server-sdk
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
      - ./basyx/rules/sm_registry_rbac_rules.json:/workspace/config/rbac_rules.json
    restart: always
    networks:
        - basyx-java-server-sdk
  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery
    volumes:
      - ./basyx/aas-discovery.properties:/application/application.properties
      - ./basyx/rules/aas_discovery_rbac_rules.json:/application/rbac_rules.json
    ports:
      - '8084:8081'
    restart: always
    networks:
        - basyx-java-server-sdk
  aas-web-ui:
    image: eclipsebasyx/aas-gui:v2-240515
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://localhost:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8083/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
      AAS_DISCOVERY_PATH: http://localhost:8084/lookup/shells
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
    networks:
        - basyx-java-server-sdk
  keycloak:
      container_name: keycloak
      build:
        context: ./keycloak
      ports:
        - 9095:9095
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_HTTP_PORT=9095
        
      networks:
        - basyx-java-server-sdk
networks:
  basyx-java-server-sdk:
    name: basyx-java-server-sdk
    driver: bridge
