/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    OutputView: typeof import('./src/components/OutputView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./src/components/StartPage.vue')['default']
    Theme: typeof import('./src/components/Theme.vue')['default']
  }
}
